### ISSUE TITLE
Trouble getting camera to work

### ISSUE THREAD

**Issue by berto10** [derricw/pysentech#2]
Hello, I'm trying to use python to capture images with a Sentech camera. However, I get the error as seen in the attached image below. Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/37448045/42902831-db6e47de-8a9d-11e8-9784-7442ce0cd8b0.png)

Thanks, 
Berto

**Comment by derricw** [comment]
You seem to be specifying the path to your SDK folder as "sentch/sdk/folder".  I think it is unlikely that this is the actually path of your downloaded Sentech USB SDK..
